---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: ansiblevol1
      vserver: svm_auto_data
      aggregate_name: n1_sas_1
      size: 10
      size_unit: gb
      comment: ansible created volume
      hostname: "10.1.1.10"
      username: "admin"
      password: "Netapp1!"
      https: true
      validate_certs: false
